#!/usr/bin/env bash
set -euo pipefail

XDG_CACHE_HOME="${XDG_CACHE_HOME:-${XDG_HOME:-${HOME}}/.cache}"
TF_INSTALL_VERSIONS_DIR="${XDG_CACHE_HOME}/terraform/versions"

find_up() {
    name="${1}"
    search_path="${PWD}"
    while [[ "${search_path}" != "" ]]; do
        if [[ -f "${search_path}/${name}" ]]; then
            echo "${search_path}/${name}"
            return 0
        fi
        search_path="${search_path%/*}"
    done
}

version_file="$(find_up ".terraform-version")"

if [[ -z "${version_file}" ]]; then
    echo "TERRAFORM-INSTALL: No .terraform-version file found." >&2
    exit 100
fi

version=$(< "${version_file}")

if [[ -z "${version}" ]]; then
    echo "TERRAFORM-INSTALL: No version defined in version file." >&2
    exit 101
fi

if [ ! -f "${TF_INSTALL_VERSIONS_DIR}/${version}/terraform" ]; then
    echo "TERRAFORM-INSTALL: Terraform ${version} executable not found." >&2
    echo "TERRAFORM-INSTALL: You can install terraform by running 'terraform-install'" >&2
    exit 102
fi

exec "${TF_INSTALL_VERSIONS_DIR}/${version}/terraform" "$@"
